### ISSUE TITLE
Future of this package

### ISSUE THREAD

**Issue by Cody-G** [ajkeller34/UnitfulPlots.jl#6]
I discovered this package through [this](https://github.com/JuliaPlots/Plots.jl/issues/460) thread, and I've found it useful!  Given that there hasn't been new development of this package in a while and there seemed to be some disagreement about how plotting Unitful quantities should work, I'm wondering about the future of this package.  Has there been any more discussion of this, maybe in another thread that I've missed?  I could imagine working on some improvements to this package but want to make sure my efforts wouldn't be wasted.  Thanks!

**Comment by ajkeller34** [comment]
Basically, I just haven't had time to work on it. I continue to use Plots.jl, though primarily in interactive cases as opposed to generating publication quality graphics. If you want to open some PRs, I'd be happy to see where you take it.

**Comment by Cody-G** [comment]
Great, just wanted to make sure.  I'm having a problem plotting matrices.  I didn't work on a fix yet, but I can look into that.  I'll start a different issue.  Thanks!
