### ISSUE TITLE
Julia 0.6 use of UnitfulPlots' recipes

### ISSUE THREAD

**Issue by goedman** [ajkeller34/UnitfulPlots.jl#8]
Hi Andrew,

Should the call to ustrip(val.) be replaced by ustrip.(val.) in UnitfulPlots.jl? 

I've only seen the problem when I add units to the tick marks (which is discussed in #5 and I agree that a better approach is to extract the units and use them in the axes labels).

It's a simple change but I can make a PR if that's easier.

Regards,
Rob

**Comment by ajkeller34** [comment]
Closed by #9
